#!/usr/bin/env python3
"""ETA-aware watcher for an experiment's wandb runs.

Strategy: don't blind-poll. Project ETA from each run's current `train/global_step`
+ `_runtime`, sleep until ~70% of the slowest ETA, then poll every poll_every_s
seconds until every named run is in a terminal state (or hard deadline hits).
Writes status JSON every poll iteration, and a staged ## Result markdown block
on terminal — never edits plan.md directly.

Usage:
    uv run python watch_runs.py <slug> [--target_steps 20000]
                                       [--min_poll_s 60]
                                       [--max_wait_min 120]

Run via Bash(run_in_background=True) so it survives between conversation turns.
Output files:
    experiments/<slug>/logs/05-watch.json          live status (overwritten each poll)
    experiments/<slug>/logs/05-staged-result.md    draft ## Result on terminal
    experiments/<slug>/logs/05-watch.log           stdout/stderr for debugging
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
import time
from pathlib import Path

_HERE = Path(__file__).resolve().parent  # skills/wandb-driven-dev/scripts
sys.path.insert(0, str(_HERE.parent.parent / "wbagent" / "scripts"))
sys.path.insert(0, str(_HERE))

from wandb_helpers import get_api  # noqa: E402
from wdd_helpers import read_config  # noqa: E402

TERMINAL_STATES = {"finished", "failed", "crashed", "killed"}


def log(msg: str) -> None:
    print(f"[{dt.datetime.now().isoformat(timespec='seconds')}] {msg}", flush=True)


def find_experiment_runs(api, project: str, slug: str):
    """Find non-smoke runs whose name matches `exp-<slug>-variant-*` or `exp-<slug>-baseline`."""
    pattern = re.compile(rf"^exp-{re.escape(slug)}-(variant(-.+)?|baseline)$")
    runs = api.runs(project, filters={"display_name": {"$regex": f"^exp-{re.escape(slug)}-"}}, per_page=20)
    return [r for r in runs if pattern.match(r.name)]


def per_run_eta_seconds(run, target_steps: int) -> float | None:
    """Project remaining wall-clock for one running run. None if not enough signal."""
    if run.state != "running":
        return 0.0 if run.state in TERMINAL_STATES else None
    step = run.summary_metrics.get("train/global_step") or 0
    elapsed = run.summary_metrics.get("_runtime") or 0
    if step <= 0 or elapsed <= 0 or step >= target_steps:
        return None
    return elapsed * (target_steps - step) / step


def snapshot_status(api, runs, project: str, target_steps: int, decision_metrics: list[str]) -> dict:
    """Refetch each run and build a status dict."""
    out = {"now": dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds"), "runs": []}
    fresh_max_eta = 0.0
    any_running = False
    for r in runs:
        run = api.run(f"{project}/{r.id}")
        eta = per_run_eta_seconds(run, target_steps)
        running = run.state == "running"
        any_running = any_running or running
        if eta and eta > fresh_max_eta:
            fresh_max_eta = eta
        out["runs"].append({
            "id": run.id,
            "name": run.name,
            "state": run.state,
            "url": run.url,
            "step": run.summary_metrics.get("train/global_step"),
            "runtime_s": run.summary_metrics.get("_runtime"),
            "eta_s": eta,
            "metrics": {k: run.summary_metrics.get(k) for k in decision_metrics},
        })
    out["any_running"] = any_running
    out["max_eta_s"] = fresh_max_eta
    return out


def write_status(status: dict, path: Path) -> None:
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(status, indent=2))
    os.replace(tmp, path)


def write_staged_result(status: dict, slug: str, decision_metrics: list[str], path: Path) -> None:
    """On terminal, write a draft ## Result block. Never touches plan.md directly."""
    runs = status["runs"]
    crashed = [r for r in runs if r["state"] in {"failed", "crashed", "killed"}]
    finished = [r for r in runs if r["state"] == "finished"]

    headline = decision_metrics[0] if decision_metrics else None

    lines = [
        f"# Staged ## Result for {slug}",
        f"_Generated by watch_runs.py at {status['now']}._",
        "",
        f"**Run states:** {len(finished)} finished, {len(crashed)} crashed/failed, {len(runs) - len(finished) - len(crashed)} other.",
        "",
        "## Result",
        "**Verdict:** TODO — fill in pass / fail / inconclusive after reviewing the table below.",
        "",
        "**Key numbers:**",
        "",
        "| Run | State | Step |" + "".join(f" {m} |" for m in decision_metrics),
        "|---|---|---|" + "---|" * len(decision_metrics),
    ]
    if headline:
        runs_sorted = sorted(runs, key=lambda r: (r["metrics"].get(headline) is None, r["metrics"].get(headline) or float("inf")))
    else:
        runs_sorted = runs
    for r in runs_sorted:
        cells = [r["name"], r["state"], str(r.get("step") or "-")]
        for m in decision_metrics:
            v = r["metrics"].get(m)
            cells.append(f"{v:.4f}" if isinstance(v, (int, float)) else "-")
        lines.append("| " + " | ".join(cells) + " |")
    lines += [
        "",
        "**Against hypothesis:** TODO — confirmed / falsified / inconclusive (reference plan.md `## Falsifier`).",
        "",
        "**Merge recommendation:** TODO.",
        "",
        "---",
        "",
        f"Splice the `## Result` block above into `experiments/{slug}/plan.md` after reviewing.",
    ]
    if crashed:
        lines += [
            "",
            "**⚠ Crashed runs need investigation:**",
            *(f"- `{r['name']}` ({r['state']}): {r.get('url', '')}" for r in crashed),
        ]
    path.write_text("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("slug", help="Experiment slug (matches the exp/<slug> tag)")
    ap.add_argument("--target_steps", type=int, default=20000, help="Step budget per run")
    ap.add_argument("--min_poll_s", type=int, default=60,
                    help="Floor for the adaptive sleep between polls (default 60s)")
    ap.add_argument("--max_wait_min", type=int, default=90, help="Hard deadline from script start")
    ap.add_argument("--initial_sleep_frac", type=float, default=0.7,
                    help="Sleep until this fraction of estimated max ETA before the first poll")
    ap.add_argument("--poll_eta_frac", type=float, default=0.5,
                    help="Each subsequent poll sleeps this fraction of the current max ETA "
                         "(adaptive: long waits early, short near terminal)")
    ap.add_argument("--logs_dir", default=None,
                    help="Absolute path to logs/ dir (default: experiments/<slug>/logs/ relative to cwd). "
                         "Set when running from a checkout where the worktree's experiments/ lives elsewhere.")
    args = ap.parse_args()

    cfg = read_config()
    if cfg is None:
        sys.exit("FAIL: .claude/wandb-driven-dev.local.md missing — run skill setup first")
    project = cfg["wandb_project"]
    decision_metrics = cfg["metrics"]["decision"]

    logs_dir = Path(args.logs_dir) if args.logs_dir else Path(f"experiments/{args.slug}/logs")
    logs_dir.mkdir(parents=True, exist_ok=True)
    status_path = logs_dir / "05-watch.json"
    staged_path = logs_dir / "05-staged-result.md"

    api = get_api()
    runs = find_experiment_runs(api, project, args.slug)
    if not runs:
        sys.exit(f"FAIL: no runs match exp-{args.slug}-* in {project}")
    log(f"Watching {len(runs)} runs: {[r.name for r in runs]}")

    deadline = time.time() + args.max_wait_min * 60

    # --- ETA-aware initial sleep ---
    status = snapshot_status(api, runs, project, args.target_steps, decision_metrics)
    write_status(status, status_path)
    if status["any_running"] and status["max_eta_s"] > 0:
        sleep_s = max(60, int(status["max_eta_s"] * args.initial_sleep_frac))
        sleep_s = min(sleep_s, max(60, int(deadline - time.time() - 60)))
        log(f"Initial sleep {sleep_s}s (max_eta={status['max_eta_s']:.0f}s, frac={args.initial_sleep_frac})")
        time.sleep(sleep_s)

    # --- Adaptive poll loop ---
    while time.time() < deadline:
        status = snapshot_status(api, runs, project, args.target_steps, decision_metrics)
        write_status(status, status_path)
        log(f"Poll: any_running={status['any_running']} max_eta={status['max_eta_s']:.0f}s")
        if not status["any_running"]:
            log("All runs terminal — staging result.")
            write_staged_result(status, args.slug, decision_metrics, staged_path)
            return
        next_sleep = max(args.min_poll_s, int(status["max_eta_s"] * args.poll_eta_frac))
        next_sleep = min(next_sleep, max(args.min_poll_s, int(deadline - time.time() - 30)))
        log(f"Next sleep {next_sleep}s")
        time.sleep(next_sleep)

    log("Hard deadline reached — staging partial result.")
    write_staged_result(status, args.slug, decision_metrics, staged_path)


if __name__ == "__main__":
    main()
